export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SET_PAGE = 'SET_PAGE'

export const ATTACK_ADDED = 'ATTACK_ADDED'
export const ATTACK_ERROR = 'ATTACK_ERROR'

export const MACHINE_ADDED = 'MACHINE_ADDED'
export const MACHINE_ERROR = 'MACHINE_ERROR'

export const PLATFORM_ADDED = 'PLATFORM_ADDED'
export const PLATFORM_ERROR = 'PLATFORM_ERROR'

export const ATTACKS_FOUND='ATTACKS_FOUND'
export const ATTACKS_NOT_FOUND='ATTACKS_NOT_FOUND'

export const MACHINE_FOUND = 'MACHINE_FOUND'
export const MACHINE_NOT_FOUND = 'MACHINE_NOT_FOUND'

export const PLATFORM_FOUND = 'PLATFORM_FOUND'
export const PLATFORM_NOT_FOUND = 'PLATFORM_NOT_FOUND'

export const SESSIONS_FOUND = 'SESSIONS_FOUND'
export const SESSIONS_NOT_FOUND = 'SESSIONS_NOT_FOUND'

export const EVALUATION_FOUND = 'EVALUATION_FOUND'
export const EVALUATION_NOT_FOUND = 'EVALUATION_NOT_FOUND'

export const ASSIGNED = 'ASSIGNED'
export const NOT_ASSIGNED = 'NOT_ASSIGNED'

export const USERS_NOT_FOUND= 'USERS_NOT_FOUND'
export const USERS_FOUND = 'USERS_FOUND'

export const CANDIDATE_ADDED = 'CANDIDATE_ADDED'
export const CANDIDATE_NOT_ADDED = 'CANDIDATE_NOT_ADDED'

export const ORGANIZATION_FOUND = 'ORGANIZATION_FOUND'
export const ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND'

export const MANAGERS_FOUND = 'MANAGERS_FOUND'
export const MANAGERS_NOT_FOUND = 'MANAGERS_NOT_FOUND'

export const CANDIDATE_FOUND = "CANDIDATE_FOUND"
export const CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND"

export const MANAGER_ADDED = 'MANAGER_ADDED'
export const MANAGER_NOT_ADDED = 'MANAGER_NOT_ADDED'

export const USER_DELETED = 'USER_DELETED'
export const USER_NOT_DELETED = 'USER_NOT_DELETED'

export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGOUT = 'LOGOUT'

export const GET_USER_ROFILE = 'GET_USER_ROFILE'
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

//visualization
export const VIS_TACTICS_FOUND = 'VIS_TACTICS_FOUND';
export const VIS_TACTICS_NOT_FOUND = 'VIS_TACTICS_NOT_FOUND';

export const VIS_ASSIGNMENTS_ATTEMPTED_STATUS_FOUND = 'VIS_ASSIGNMENTS_ATTEMPTED_STATUS_FOUND';
export const VIS_ASSIGNMENTS_ATTEMPTED_STATUS_NOT_FOUND = 'VIS_ASSIGNMENTS_ATTEMPTED_STATUS_NOT_FOUND';

export const VIS_ASSIGNMENTS_HISTORY_FOUND = 'VIS_ASSIGNMENTS_HISTORY_FOUND';
export const VIS_ASSIGNMENTS_HISTORY_NOT_FOUND = 'VIS_ASSIGNMENTS_HISTORY_NOT_FOUND';

export const VIS_SESSIONS_FOUND = 'VIS_SESSIONS_FOUND';
export const VIS_SESSIONS_NOT_FOUND = 'VIS_SESSIONS_NOT_FOUND';

export const VIS_PERFORMANCE_FOUND = 'VIS_PERFORMANCE_FOUND';
export const VIS_PERFORMANCE_NOT_FOUND = 'VIS_PERFORMANCE_NOT_FOUND';

export const VIS_MITRE_PERFORMANCE_FOUND = 'VIS_MITRE_PERFORMANCE_FOUND';
export const VIS_MITRE_PERFORMANCE_NOT_FOUND = 'VIS_MITRE_PERFORMANCE_NOT_FOUND';


//CHAT
export const  COMMUNITY_CHAT="COMMUNITY_CHAT";
export const  USER_CONNECTED="USER_CONNECTED";
export const  MESSAGE_RECIEVED="MESSAGE_RECIEVED";
export const  MESSAGE_SENT="MESSAGE_SENT";
export const USER_DISCONNECTED="USER_DISCONNECTED";
export const TYPING="TYPING";
export const VERIFY_USER="VERIFY_USER";
export const PASS_VERIFY_USER_TO_MIDDLEWARE="PASS_VERIFY_USER_TO_MIDDLEWARE";
export const PASS_PRIVATE_MESSAGE_USER_TO_MIDDLEWARE="PASS_PRIVATE_MESSAGE_USER_TO_MIDDLEWARE";
export const PASS_MESSAGE_SENT_TO_MIDDLEWARE="PASS_MESSAGE_SENT_TO_MIDDLEWARE";
export const PASS_TYPING_TO_MIDDLEWARE ="PASS_TYPING_TO_MIDDLEWARE";
export const CHAT_LOGOUT="CHAT_LOGOUT";
export const PRIVATE_MESSAGE="PRIVATE_MESSAGE";
export const ADD_CHAT="ADD_CHAT"
export const UPDATE_CHAT="UPDATE_CHAT"
export const UPDATE_USERS_STATUS="UPDATE_USERS_STATUS"
export const CONNECT="connect";
export const SET_CHAT_USER="SET_CHAT_USER"
export const SET_ACTIVE_CHAT="SET_ACTIVE_CHAT"
export const UPDATE_OFFLINE_STATUS="UPDATE_OFFLINE_STATUS"
export const SET_OFFLINE_STATUS="SET_OFFLINE_STATUS"
export const CONNECTION_ESTABLISHED="CONNECTION_ESTABLISHED"
export const GET_ONLINE_USERS="GET_ONLINE_USERS"
export const GET_AVAILABLE_CONTACTS="GET_AVAILABLE_CONTACTS"